### ISSUE TITLE
Can not addOnPageChangeListener to the ViewPager

### ISSUE THREAD

**Issue by Lee-swifter** [H07000223/FlycoBanner_Master#11]
This Banner is a good lib, but if i put this into a `SwipeRefreshLayout`, there will be a trouble: whenever I'm going to swipe left / right to switch between pages the scrolling is too sensitive.

So I need to solve this bug by adding a `PageChangListener` to the `ViewPager`, but this will case a crash, even I do nothing in `PageChangeListener`.

This is the code I add in SimpleImageBanner:
``````````````````````
public void setSwipeRefresh(final SwipeRefreshLayout swipeRefreshLayout) {
        vp.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

            }

            @Override
            public void onPageSelected(int position) {

            }

            @Override
            public void onPageScrollStateChanged(int state) {
                swipeRefreshLayout.setEnabled(state == ViewPager.SCROLL_STATE_IDLE );
            }
        });
    }
`````````````````````````

and the crash log:
````````````````````````````````
java.lang.NullPointerException
            at com.flyco.banner.widget.LoopViewPager.LoopViewPager$1.onPageScrolled(LoopViewPager.java:166)
            at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1777)
            at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1750)
            at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1671)
            at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:577)
            at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1638)
            at android.view.View.layout(View.java:14849)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
            at android.view.View.layout(View.java:14849)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:14849)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.widget.ScrollView.onLayout(ScrollView.java:1468)
            at android.view.View.layout(View.java:14849)
`````````````````````````````````

Is there anyway I can `addOnPageChangeListener` to the `ViewPager` ?

**Comment by Lee-swifter** [comment]
I got the answer,  I should use `BaseBanner.addOnPageChangeListener`, not the `vp.addOnPageChangeListener`.
