### ISSUE TITLE
重新setSource后onTitleSlect函数中的position参数没有重置

### ISSUE THREAD

**Issue by Lee-swifter** [H07000223/FlycoBanner_Master#13]
如果新设置进去的list长度比原来的list短，而且当时的position要大于现在的list长度，程序在回调`onTitleSlect`函数时就会发生异常：
``````````````````
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.yunwang.yunwang.view.SimpleImageBanner.onTitleSlect(SimpleImageBanner.java:43)
       at com.flyco.banner.widget.Banner.base.BaseBanner.startScroll(BaseBanner.java:361)
``````````````````
我觉得这个事情不应该由使用者进行判断，程序应该在`public T setSource(List<E> list)`中重置一下`currentPositon`

**Comment by H07000223** [comment]
已在最新2.0.0修复~
