### ISSUE TITLE
The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChan

### ISSUE THREAD

**Issue by ehaahe** [H07000223/FlycoBanner_Master#35]
Caused by: java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131492870, class android.widget.ListView) with Adapter(class com.by.czw.adapter.LotteryDetailNormalAdapter)]
2    at android.widget.ListView.layoutChildren(ListView.java:1582)
3    at android.widget.AbsListView.onLayout(AbsListView.java:2190)
4    at android.view.View.layout(View.java:16707)
5    at android.view.ViewGroup.layout(ViewGroup.java:5476)
6    at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.layoutChildren(SwipeToLoadLayout.java:1083)
7    at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.fixCurrentStatusLayout(SwipeToLoadLayout.java:1146)
8    at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.autoScrollFinished(SwipeToLoadLayout.java:1353)
9    at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.access$1800(SwipeToLoadLayout.java:19)
10    at com.aspsine.swipetoloadlayout.SwipeToLoadLayout$AutoScroller.finish(SwipeToLoadLayout.java:1562)
11    at com.aspsine.swipetoloadlayout.SwipeToLoadLayout$AutoScroller.run(SwipeToLoadLayout.java:1545)
12    at android.os.Handler.handleCallback(Handler.java:739)
13    at android.os.Handler.dispatchMessage(Handler.java:95)
14    at android.os.Looper.loop(Looper.java:179)
15    at android.app.ActivityThread.main(ActivityThread.java:5672)
16    at java.lang.reflect.Method.invoke(Native Method)
17    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
18    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)

**Comment by abhimuktheeswarar** [comment]
I also got the same error, any solution?
